My branch
SWE-CS410/5541-Spring23CodeReviewActivity pull request #6
Opened 2023-06-15 18:12 UTC by GonGustavo

2023-06-15 18:54 UTC, dantzlerdc requested changes
check (jacoco-check) on project UnitTestAssignment: Coverage checks have not been met. See log for details. 
The build failed due to jacoco not meeting the coverage requirement

2023-06-17 06:51 UTC, dantzlerdc commented on src/main/java/StringManipulation.java
> +            throw new IllegalArgumentException("Invalid start or end word");
I ran the test coverage on my local machine to see what test coverage issues jacoco is complaining about.
I was not able to upload a screen shot, but basically it identifies those lines that throw an exception as not being accounted for. Check you test cases to see if you check for those exceptions.

2023-06-17 06:55 UTC, dantzlerdc commented on src/test/java/StringManipulationTest.java
> +        assertEquals("Bri", manipulatedstring.removeNthCharacter(5, false));
You are missing test cases to check for Exceptions being thrown. For example
 @Test //assert throws IllegalArgumentException if n == 0
    public void testRemoveNthCharacter3() {
        manipulatedstring.setString("123");
        assertThrows(IllegalArgumentException.class, () -> {manipulatedstring.removeNthCharacter(0,true);});
    }

2023-06-17 06:56 UTC, dantzlerdc requested changes
You need to add test cases to cover the possible Exceptions that can be thrown.
For example:
 @Test //assert throws IllegalArgumentException if n == 0
    public void testRemoveNthCharacter3() {
        manipulatedstring.setString("123");
        assertThrows(IllegalArgumentException.class, () -> {manipulatedstring.removeNthCharacter(0,true);});
    }

2023-06-19 19:33 UTC, GonGustavo commented
Thank you Dewayne, after reviewing your feedback I was able to correct my code and get it to pass in Travis.

2023-06-20 05:22 UTC, dantzlerdc commented
Great, then I will go ahead a close this ticket.

2023-06-20 05:22 UTC, closed without merging